services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:{$IMAGE_VERSION}
    container_name: $CONTAINER_NAME
    environment:
      SA_PASSWORD: $ADMIN_PASSWORD
      ACCEPT_EULA: Y
    ports:
      - "${PORT_IN}:${PORT_OUT}"
    volumes:
      - ./data:${DATA_LOCATION}
      - ./log:${LOGS_LOCATION}
      - ./secrets:${SECRETS_LOCATION}
